# Generated by Django 5.1.4 on 2024-12-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='nome',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
